import Head from "next/head";
import Header from "./Header";
import Footer from "./Footer";

const layout = ({ children, paginas, guitarra }) => {
  return (
    <div>
      <Head>
        <title>GuitarLA - {paginas}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@400;700;900&display=swap" rel="stylesheet"/>
      </Head>
      <Header
        guitarra={guitarra}
      />
      {children}
      <Footer/>
    </div>
  );
};

layout.defaultProps = {
  guitarra: null
}

export default layout;
